export const EDU_ORGS_GENERAL_OPTION_VALUE = null;

export const VALIDATION_ERROR_CODE = "VALIDATION_FAILED";
export const VALIDATION_ERROR_EXTENSIONS_KEY = "validationErrors";

export const AUTHENTICATION_ERROR_CODE = "UNAUTHENTICATED";

export const NEW_USER_ERROR_CODE = "NEW_USER";

export const EXISTING_USER_ERROR_CODE = "EXISTING_USER";
